server:
  port: 13340
  servlet:
    context-path: /kt-dxp
    encoding:
      charset: utf-8
      enabled: true
      force: true
spring:
  application:
    name: kt_dxp
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  datasource:
    hikari:
      connection-timeout: 30000
      validation-timeout: 30000
      minimum-idle: 2
      max-lifetime: 240000
      maximum-pool-size: 5
      idle-timeout: 10000
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  batch:
    enable : false
    job:
      enabled: true
#    jdbc:
#      initialize-schema: always
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jasypt:
  key: ${jasypt-key}
firebase:
  service-account: #
jwt:
  auth-key: #

sp:
  did:
    service-code: #
    base-url: #
rc:
  mileage:
    auth-key: #
    base-url: #

#logging:
#  config: classpath:./logback/logback-spring.xml
#loggin:
#  level:
#    org:
#      springframework: DEBUG

#logging:
#  level:
#    root: trace
# open-in-view(\ud639\uc740 Open-Session-In-View(OSIV))
# true(\uae30\ubcf8\uac12) : \uc0ac\uc6a9\uc790\uc5d0\uac8c \uc751\ub2f5 \ub610\ub294 view\uac00 \ub80c\ub354\ub9c1\ub420 \ub54c\uae4c\uc9c0 \uc601\uc18d\uc131 \ucee8\ud14d\uc2a4\ud2b8 \uc720\uc9c0
# false : \ud2b8\ub79c\uc81d\uc158\uc774 \uc885\ub8cc\ub420 \ub54c \uc601\uc18d\uc131 \ucee8\ud14d\uc2a4\ud2b8 \uc885\ub8cc
nice:
  site-code: #
  site-pw: #
  req-num: #

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: #
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: #
    password: #
file:
  upload-path: /notice/file
  path: neighbor21file
#  base-path: C:/home/ccdid
  base-path: /home/ccdid
swagger:
  enabled: true

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: #
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: #
    password: #
file:
  base-path: /home/ccdid
swagger:
  enabled: false